name: htop-pro
base: core22
version: '2026.7.2'
summary: Lightweight system monitor with CPU, RAM, network and internet speed meter
description: Real-time CPU usage, RAM usage, internet speed and network activity through beautiful, interactive graphs.
grade: stable
confinement: strict

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/pyqt5-runtime-core22-lite

apps:
  htop:
    command: bin/desktop-launch python3 $SNAP/htop.py
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - unity7
      - wayland
      - opengl
      - hardware-observe
      - network-status
    desktop: htop.desktop
    environment:
      DISABLE_WAYLAND: 1

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime-core22-lite:
    interface: content
    target: $SNAP/pyqt5-runtime-core22-lite
    default-provider: pyqt5-runtime-core22-lite


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/htop.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/htop.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/htop.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  htop:
      plugin: python
      source: .
      python-packages:
        - psutil
        - py-cpuinfo
        - cryptography
        - requests